main: com.minegusta.minegustastuff.MinegustaPlugin
author: janie177
version: ${project.version}
softdepend: [WorldGuard]
name: MinegustaStuff
commands:
   race:
      description: Races help
      usage: /Race
      default: true
      aliases: [races, classes, class, elf, dwarf, human, enderborn]
